### PR TITLE
fix color ordering in DisplayNetwork

### PR DESCRIPTION
**Pull request by NikkyAI**

### CODE REVIEW

**Comment by sellicott** [comment]
I think it would be better to only register one parameter, say "led_color_order" or similar. This value can take on values -1, 0, 1, 2, 3. Where -1 is default and the other options map to "RGBA", "RGB", etc. Note that I am not suggesting a value mapping (other than -1 as default), that was just for illustration purposes.

**Comment by cnlohr** [comment]
wahaaaaaaaa.... Oh boy.  Ok, so for RGB, I believe you can get all variations of RGB, BGR, RGB, etc... by saying is BRG and shifting the first LED byte back and forth. 

I do think there may be value in coming up with a truly generic method, perhaps ->

```
led_configuration=(numeric)
led_per_chan=(numeric)
```

Where you map it as a bit of a longer bitmask.

You extract red, green, blue and yellow into variables:
```
uint8_t r = LEDs[i]&0xff;
uint8_t g = (LEDs[i]>>8)&0xff;
uint8_t b = (LEDs[i]>>16)&0xff;
uint8_t y = (LEDs[i]>>24)&0xff;
```

Then, you get your metadata:

```
int redpos = (led_configuration>>0)&0xf;
int grnpos = (led_configuration>>4)&0xf;
int blupos = (led_configuration>>8)&0xf;
int yelpos = (led_configuration>>12)&0xf;
```

Then, you mix the LEDs in:
```
uint8_t * outdata = outdatastart + lednumber * led_per_chan;
if( redpos < 15 ) outdata[redpos] = r;
if( grnpos < 15 ) outdata[grnpos] = g;
if( blupos < 15 ) outdata[blupos] = b;
if( yelpos < 15 ) outdata[yelpos] = y;
```

While there are a lot of if's here, ColorChord2 code will always be running on a modern-ish processor which should at the least have some form of branch prediction, and thus not be an issue.

I didn't want to invalidate all the older config files.  You could put in an autodetect to see if is_bgr is set, and if so, set `led_configuration` appropriately.  In that case it would be: `led_configuration = 0xf021 (‭61,473‬)` or if none are set, like normal RGB output, you could set it to be 0xf210`

ACTUALLY thinking about it, why not just have redpos, grnpos and blupos as being separate configuration items, then it could be if `redpos >= 0` then... Yeah, I like that better.

**Comment by NikkyAI** [comment]
i have the usecase of a led grid that is left-to-right top-to-bottom
so shifting around seems like it would offset each row by one pixel

currently i seem to have to give it x + 1 LEDs i nthe config otherwise the last pixel is not sent, but that might be not related

**Comment by CaiB** [comment]
From what I see, I think the shifting is just taking the 32-bit value representing all 4 colours, and turning it into 4 8-bit values, not actually changing the positions of the pixels.

i.e.
```
uint x = 352301410 // We are given this colour to output
|-------------- 32-bit -------------|
|    Y   |    B   |    G   |    R   |
 00010100 11111111 10110001 01100010 // binary view of x
                  \________
x >>= 8                    \
 00000000 00010100 11111111 10110001 // shifted right 8 bit positions

x &= 0b11111111 // this is 0xFF
 00000000 00000000 00000000 10110001 // all but the bottom 8 bits chopped off

g = (byte)x // put it into the right size variable
|  8-bit |
 10110001 // same as above, just with the 24 extra 0s trimmed

g = 177 // This is what was in the G area above.
```

With this we can extract the second group of 8 bits (from the right).

He's using the same idea, just applying it to groups of 4 bits, and on the configuration value instead of colour data. Then using the output of that to determine where in the output to put each of the red, green, blue, and yellow.

Sorry if I misunderstood your question.

**Comment by cnlohr** [comment]
In retrospect, we should probably just say:

`num_bytes_per_led=` and have
`red_byte_pos=`
`green_byte_pos=`
and
`blue_byte_pos=` 

At least to me that seems easiest.

**Comment by NikkyAI** [comment]
i guess when someone messes up and says all byte_pos are at the same position then it falls back to `r > b > g` ?

**Comment by cnlohr** [comment]
I don't know if there needs to be a fallback... It may make most sense to just do the dumb thing, wrongly.

**Comment by NikkyAI** [comment]
well since CaiB/master was merged back to cnlohr/master having this PR open here makes no sense.. and discussion can continue in discord anyways

**Pull request closed without merging**
